#!/system/bin/sh
#

A2SD_ACTIVE=`getprop lk.a2sd.active`

if [ "$A2SD_ACTIVE" != 1 ];
then
    # replace symlinks with directories so we can boot without sd
    for i in app app-private;
    do
       if [ -h /data/$i ];
       then
            rm -r /data/$i;
            mkdir /data/$i;
            busybox chown 1000:1000 /data/$i;
            busybox chmod 771 /data/$i;
        fi;
    done;
fi;

A2SD_MOVE_DC_ACTIVE=`getprop lk.a2sd.move_dc_active`

if [ "$A2SD_MOVE_DC_ACTIVE" != 1 ];
then
    # replace symlinks with directories so we can boot without sd
    for i in dalvik-cache;
    do
       if [ -h /data/$i ];
       then
            rm -r /data/$i;
            mkdir /data/$i;
            busybox chown 1000:1000 /data/$i;
            busybox chmod 771 /data/$i;
        fi;
    done;
fi;
