#!/system/bin/sh
#
# Ugly hack, to 
# - get bluetooth address
# - fix missing initialization
#

#
# Safe Mode:
# you can add your bt address here
#
# use capitalized letters, for example:
# BD_ADDR="AA:BB:CC:DD:EE:00"
#

#BD_ADDR="00:00:00:00:00:00"

setprop service.brcm.bt.btld 0
start btld > /dev/null 2>/dev/null

while [ "`logcat -d *:I|grep BDA|grep btl_cfg_get_bdaddr|grep -v busybox|wc -l`" -eq 0 ];
do
    sleep 1;
done

if [ -z "${BD_ADDR}" ] && [ -f "/data/bd_addr" ]
then
    setprop ro.bt.bdaddr_path "/data/bd_addr"
fi

if [ -n "${BD_ADDR}" ]
then
    echo "${BD_ADDR}" > /data/bd_addr
    setprop ro.bt.bdaddr_path "/data/bd_addr"
fi

stop btld
sleep 5;
killall -9 btld > /dev/null 2>/dev/null
